name: Build and test project
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    name: Check code formatting
    steps:
    - uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - run: cd obsinflate
    - run: npm install
    - run: npm run format:check
  build:
    runs-on: ubuntu-latest
    name: Build project
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: cd obsinflate
      - run: npm install
      - run: npm run build
  test:
    runs-on: ubuntu-latest
    name: Test project
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: cd obsinflate
      - run: npm install
      - run: npm run test:unit
  bundle:
    runs-on: ubuntu-latest
    name: Test the project bundling
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: cd obsinflate
      - run: npm install
      - run: npm run bundle
  bundle-helloworld:
    runs-on: ubuntu-latest
    name: Test the hello world samples bundling
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: cd obsinflate
      - run: npm install
      - run: npm run bundle:helloworld