name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    name: Builds the release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.9.0
      - run: npm ci
        working-directory: obsinflate
      - env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run release
        working-directory: obsinflate