name: Build and test project
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    name: Check code formatting
    steps:
    - uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20.9.0
    - run: npm ci
      working-directory: obsinflate
    - run: npm run format:check
      working-directory: obsinflate
  build:
    runs-on: ubuntu-latest
    name: Build project
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
      - run: npm ci
        working-directory: obsinflate
      - run: npm run build
        working-directory: obsinflate
  test:
    runs-on: ubuntu-latest
    name: Test project
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
      - run: npm ci
        working-directory: obsinflate
      - run: npm run test:unit
        working-directory: obsinflate
  bundle:
    runs-on: ubuntu-latest
    name: Test the project bundling
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
      - run: npm ci
        working-directory: obsinflate
      - run: npm run bundle
        working-directory: obsinflate
  bundle-helloworld:
    runs-on: ubuntu-latest
    name: Test the hello world samples bundling
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
      - run: npm ci
        working-directory: obsinflate
      - run: npm run bundle:helloworld
        working-directory: obsinflate
